### ISSUE TITLE
Sonoff MQTT Alexa and Siri?

### ISSUE THREAD

**Issue by jat80** [kakopappa/arduino-esp8266-alexa-wemo-switch#15]
Hi there,

This is amazing and i'm looking at trying this out on a spare sonoff.

I currently have a few sonoffs and a slampher which i've flashed with he below code:

https://github.com/SuperHouse/BasicOTARelay/blob/master/BasicOTARelay.ino

It uses MQTT to turn it on and off and have that linked to an accessory file linked to HAP-NodeJS to use it with apples homekit software.  Works great.

The one thing with homekit devices and siri though is you have to use your phone to control it.  I would love to use an echo dot in the rooms to also control my hacked sonoff homekit devices and was thinking is there anyway to combine the two?

You code and the above code I'm currently using somehow together?

I can't code so not sure how one would go about this but incorporating MQTT into this code would be absolutely amazing.  A device that both siri and alexa can control!  Maybe finally Alexa and Siri can be friends?  lol

JT.

**Comment by 1rvy** [comment]
I use Alexa and Homebridge to control several ESP8266 devices around the house, no need for MQTT.

**Comment by jat80** [comment]
Good for you but I don't use homebridge. 

Sent from my iPhone 

On 18/02/2017, at 1:25 PM, 1rvy <notifications@github.com> wrote:

I use Alexa and Homebridge to control several ESP8266 devices around the house, no need for MQTT.

**Comment by 1rvy** [comment]
Fair enough, stay struggling with MQTT then!

**Comment by dougstrickland** [comment]
I run ESP8266 directly with Alexa, very simple.

**Comment by jat80** [comment]
Amazing....

Read the OP. 

Sent from my iPhone 

On 18/02/2017, at 2:53 PM, Doug Strickland <notifications@github.com> wrote:

I run ESP8266 directly with Alexa, very simple.

**Comment by 1rvy** [comment]
Good luck getting help with coding your sketch with that attitude.   We are informing you that we have acheived your end result through different means, but if you don't want to know how then you best start learning how to do it on your own.

**Comment by jat80** [comment]
Lol. What a douche'. 

Sent from my iPhone 

On 18/02/2017, at 8:17 PM, 1rvy <notifications@github.com> wrote:

Good luck getting help with coding your sketch with that attitude. We are informing you that we have acheived your end result through different means, but if you don't want to know how then you best start learning how to do it on your own.

**Comment by jat80** [comment]
Found these tutorials on how to control the sonoff via siri and alexa.  Enjoy :)

https://www.youtube.com/watch?v=n4MDRm2yAJg&t

https://www.youtube.com/watch?v=M4qHXoAyrRs&t
