### ISSUE TITLE
Initialize in the "On" state

### ISSUE THREAD

**Issue by dougstrickland** [kakopappa/arduino-esp8266-alexa-wemo-switch#17]
Currently the switch is initialized in the Low or Off condition.  How difficult would it be to change it so that when the software starts, the relay is On by default?

**Comment by kakopappa** [comment]
Just add

 digitalWrite(relayPin, HIGH); // turn on relay with voltage HIGH

At the end of
setup() {
.........
 digitalWrite(relayPin, HIGH); // turn on relay with voltage HIGH
}

**Comment by dougstrickland** [comment]
Of course, don't know why I didn't think of that!  Thanks!
