### ISSUE TITLE
Is there a way to make this work with Google Home?

### ISSUE THREAD

**Issue by atomi** [kakopappa/arduino-esp8266-alexa-wemo-switch#25]
Can someone point me to a Google home version? Or some documentation on the subject? 

Or consider a feature request for this I guess.

**Comment by samazw** [comment]
Google is different - not a feature request but a new project. Interested in programming yourself, of just costless consuming?


Best regards
Sascha

Am 01.01.2018 um 19:39 schrieb atomi <notifications@github.com<mailto:notifications@github.com>>:


Can someone point me to a Google home version? Or some documentation on the subject?

Or consider a feature request for this I guess.

**Comment by atomi** [comment]
I was just curious. Do you have some links on similar Google Home projects for esp8266?

**Comment by samazw** [comment]
Well, just use Google. 1st entry http://tinkerman.cat/using-google-assistant-control-your-esp8266-devices/

But I seriously think I‘ll not use Google to get results for you. Or - again -  be a programmer and share 😉

 Best regards
Sascha

Am 01.01.2018 um 22:11 schrieb atomi <notifications@github.com<mailto:notifications@github.com>>:


I was just curious. Do you have some links on similar Google Home projects for esp8266?

**Comment by atomi** [comment]
Haha, I thought you were more familiar with Google Home hardware which is why I asked. No worries. 

I think an easy way to use esp with google would be an ifttt applet that calls a webhook hosted on the esp. I'll play around with it on my side. 

Thanks.

**Comment by samazw** [comment]
Do it ;-)

Best regards
Sascha

Am 02.01.2018 um 02:37 schrieb atomi <notifications@github.com<mailto:notifications@github.com>>:


Haha, I thought you were more familiar with Google Home hardware which is why I asked. No worries.

I think an easy way to use esp with google would be an ifttt applet that calls a webhook hosted on the esp. I'll play around with it on my side.

Thanks.
