### ISSUE TITLE
Not discovered my Wemo app. Normal?

### ISSUE THREAD

**Issue by xbmcnut** [kakopappa/arduino-esp8266-alexa-wemo-switch#5]
Hi,

Thanks for writing a very cool bit of code. Got it working with Echo no problem but the device is not being discovered by other entities on my network like the Wemo app and Home Assistant. Is that normal?

**Comment by kakopappa** [comment]
Thanks 👍 

this is for Amazon Eco only.

**Comment by xbmcnut** [comment]
Thanks, thought it might be, just checking. Great work by the way. Works a treat.
